apply plugin: 'groovy'
apply plugin: "kotlin"

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation gradleApi()
    implementation localGroovy()
    implementation 'org.javassist:javassist:3.29.2-GA'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation 'commons-io:commons-io:2.11.0'

    //noinspection GradleDependency
    compileOnly 'com.android.tools.build:gradle:8.12.3'
}

sourceSets.main {
    java.srcDirs += ['../drouter-plugin-lib/src/main/java']
}

task sourcesJar(type: Jar) {
    getArchiveClassifier().set('sources')
    from sourceSets.main.allSource
}
artifacts {
    archives sourcesJar
}

version = '1.4.0'

jar {
    manifest {
        // 检测是否大于1.3.3版本,否则编译不通过
        // Please first make sure plugin-version null(current) >= 1.3.3(min support)
        attributes("plugin-version" : version)
    }
}

apply from: "./config.gradle"
apply from: "../maven_push.gradle"

tasks.getByName("publishPluginPublicationToPluginRepository").dependsOn("jar")
tasks.getByName("publishAllPublicationsToPluginRepository").dependsOn("jar")
tasks.getByName("publishPluginPublicationToMavenLocal").dependsOn("jar")
